providers:
  openai:
    base-url: "http://helicone-mock-server.internal:5150"
  anthropic:
    base-url: "http://helicone-mock-server.internal:5150"
  gemini:
    base-url: "http://helicone-mock-server.internal:5150"
  bedrock:
    base-url: "http://helicone-mock-server.internal:5150"

minio:
  host: "http://helicone-mock-server.internal:5150"

helicone:
  base-url: "http://helicone-mock-server.internal:5150"
  websocket-url: "ws://helicone-mock-server.internal:5150/ws/v1/router/control-plane"
  authentication: true
  observability: false

telemetry:
  level: info
  exporter: both
  otlp-endpoint: "http://helicone-otel-collector.internal:4317/v1/metrics"